import { _electron as electron, expect } from '@playwright/test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here,'../..');
const userData = fs.mkdtempSync(path.join(os.tmpdir(),'canvas-desktop-cuj-'));
let app;
const errors = [];
const launch = async () => {
  app = await electron.launch({args:[...(process.env.CANVAS_E2E_NO_SANDBOX ? ['--no-sandbox'] : []),path.join(root,'electron/main.cjs')],env:{...process.env,CANVAS_USER_DATA:userData},timeout:20000});
  const page = await app.firstWindow();
  page.on('pageerror', e => errors.push(e.message));
  await expect(page.locator('#connection')).toHaveText('● Connected');
  return page;
};
try {
  let page = await launch();
  await page.locator('#newHTML').click();
  await expect(page.locator('#count')).toHaveText('02');
  const frame = () => page.frameLocator('iframe.html-preview');
  await frame().locator('[data-node-id=title]').dblclick();
  await page.locator('#inlineText').fill('Human title survives agent layout');
  await page.locator('#inlineForm button[type=submit]').click();
  await expect(frame().locator('[data-node-id=title]')).toHaveText('Human title survives agent layout');
  await page.locator('#anchor').selectOption('title');
  await page.locator('#comment').fill('Keep this title; change only the layout.');
  await page.locator('#addComment').click();
  await expect(page.locator('.comment-item')).toHaveCount(1);
  await page.getByRole('button',{name:'Locate node',exact:true}).click();
  await expect(frame().locator('[data-node-id=title]')).toHaveCSS('outline-color','rgb(245, 158, 11)');
  const before = await page.locator('#htmlSource').inputValue();
  await page.locator('#prompt').fill('layout: horizontal');
  await page.locator('#run').click();
  await expect(page.locator('#status')).toContainText('Agent proposal validated');
  await expect(frame().locator('[data-node-id=root]')).toHaveCSS('flex-direction','row');
  await expect(frame().locator('[data-node-id=title]')).toHaveText('Human title survives agent layout');
  const after = await page.locator('#htmlSource').inputValue();
  await page.locator('#undo').click();
  await expect(page.locator('#htmlSource')).toHaveValue(before);
  await expect(frame().locator('[data-node-id=root]')).toHaveCSS('flex-direction','column');
  await page.locator('#redo').click();
  await expect(page.locator('#htmlSource')).toHaveValue(after);
  // A real second renderer submits against the same authority during an open draft.
  await app.evaluate(async ({BrowserWindow}) => {
    const first = BrowserWindow.getAllWindows()[0];
    const second = new BrowserWindow({show:false,width:1280,height:900,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});
    await second.loadURL(first.webContents.getURL());
  });
  const other = app.windows().find(p => p !== page);
  await expect(other.locator('#count')).toHaveText('02');
  const id = await page.locator('#selected').textContent();
  await other.locator('#components button').filter({hasText:id}).evaluate((button) => button.click());
  await frame().locator('[data-node-id=body]').dblclick();
  await page.locator('#inlineText').fill('Retained conflict draft');
  await other.locator('#prompt').fill('title: Other window title');
  await other.locator('#run').click();
  await expect(other.locator('#status')).toContainText('Agent proposal validated');
  await page.locator('#inlineForm button[type=submit]').click();
  await expect(page.locator('#inlineError')).toContainText('Revision conflict');
  await expect(page.locator('#inlineText')).toHaveValue('Retained conflict draft');
  await page.locator('#rebaseInline').click();
  await expect(page.locator('#inlineContext')).toContainText('Your draft is retained');
  await page.locator('#inlineForm button[type=submit]').click();
  await expect(frame().locator('[data-node-id=body]')).toHaveText('Retained conflict draft');
  // Removing a node orphans the comment; undo restores both source and location.
  const source = await page.locator('#htmlSource').inputValue();
  await page.locator('#htmlSource').fill(source.replace(/<h2 data-node-id="title">.*?<\/h2>/,'<h2 data-node-id="replacement">Replacement</h2>'));
  await page.locator('#editor button[type=submit]').click();
  await expect(page.getByRole('button',{name:'Node removed · historical comment'})).toBeDisabled();
  await page.locator('#undo').click();
  await expect(page.getByRole('button',{name:'Locate node',exact:true})).toBeEnabled();
  const saved = await page.evaluate(async () => { const v = await (await fetch('/api/state')).json(); return {state:v.state, revision:v.revision,events:v.events}; });
  fs.mkdirSync(path.join(root,'test-results'),{recursive:true});
  await page.screenshot({path:path.join(root,'test-results/html-cuj-desktop.png'),fullPage:true});
  await app.close(); app = null;
  page = await launch();
  const restored = await page.evaluate(async () => { const v = await (await fetch('/api/state')).json(); return {state:v.state, revision:v.revision,events:v.events}; });
  expect(restored).toEqual(saved);
  await page.locator('#components button').filter({hasText:id}).click();
  await expect(frame().locator('[data-node-id=body]')).toHaveText('Retained conflict draft');
  await page.getByRole('button',{name:'Locate node',exact:true}).click();
  await expect(frame().locator('[data-node-id=title]')).toHaveCSS('outline-color','rgb(245, 158, 11)');
  expect(errors).toEqual([]);
  console.log('PASS Electron HTML CUJ: text, layout, anchors, two-window conflict/reapply, undo/redo, orphan/restore, process restart; no renderer errors.');
} finally {
  if (app) await app.close();
  fs.rmSync(userData,{recursive:true,force:true});
}
